# Autogenerated by Wise annotation utility on 2010-09-04 20:24:14.182246

try:
    from wise.worksheet.pure_wrap import use, PureSymbol
except ImportError:
    raise Exception('Could not load Cython Pure module, perhaps it needs to be built?')

#use('logic','logic')
