# Autogenerated by Wise annotation utility on 2010-09-04 20:24:14.182246

try:
    from wise.worksheet.pure_wrap import use, PureSymbol
except ImportError:
    raise Exception('Could not load Cython Pure module, perhaps it needs to be built?')

use('logic','logic')
# logic.pure
And = PureSymbol('And')
LogicFalse = PureSymbol('False')
push_assoc_left = PureSymbol('push_assoc_left')
boolean_normal = PureSymbol('boolean_normal')
push_assoc_right = PureSymbol('push_assoc_right')
LogicTrue = PureSymbol('True')
Or = PureSymbol('Or')
