# Autogenerated by Wise annotation utility on 2010-09-15 02:17:29.566952

try:
    from wise.translators.pure_wrap import PureInterface
except ImportError:
    raise Exception('Could not load Cython Pure module, perhaps it needs to be built?')
