# -*- coding: utf-8 -*-

greek_unicode = {
         'alpha'  :          'α',
         'beta'   :          'β',
         'gamma'  :          'γ',
         'delta'  :          'δ',
         'epsilon' :         'ε',
         'varepsilon':       'ζ',
         'zeta'   :          'η',
         'eta'    :          'ϑ',
         'theta'  :          'θ',
         'vartheta':         'ι',
         'gamma'  :          'κ',
         'kappa'  :          'λ',
         'lambda' :          'μ',
         'mu'     :          'ν',
         'nu'     :          'ξ',
         'xi'     :          'ο',
         'pi'     :          'π',
         'varpi'  :          'ρ',
         'rho'    :          'σ',
         'varrho' :          'ς',
         'sigma'  :          'τ',
         'varsigma':          'υ',
         'tau'    :          'ϕ',
         'upsilon':          'φ',
         'phi'    :          'χ',
         'varphi' :          'ψ',
         'chi'    :          'ω',
         }

greek_alphabet = {
        'alpha'  :  '\\alpha',
        'beta'   :  '\\beta',
        'gamma'  :  '\\gamma',
        'delta'  :  '\\delta',
        'epsilon' :  '\\epsilon',
        'varepsilon' :  '\\varepsilon',
        'zeta'   :  '\\zeta',
        'eta'    :  '\\eta',
        'theta'  :  '\\theta',
        'vartheta' :'\\vartheta',
        'gamma'  :  '\\gamma',
        'kappa'  :  '\\kappa',
        'lambda' :  '\\lambda',
        'mu'     :  '\\mu',
        'nu'     :  '\\nu',
        'xi'     :  '\\xi',
        'pi'     :  '\\pi',
        'varpi'  :  '\\varpi',
        'rho'    :  '\\rho',
        'varrho' :  '\\varrho',
        'sigma'  :  '\\sigma',
        'varsigma' :'\\varsigma',
        'tau'    :  '\\tau',
        'upsilon':  '\\upsilon',
        'phi'    :  '\\phi',
        'varphi' :  '\\varphi',
        'chi'    :  '\\chi',
        'psi'    :  '\\psi',
        'omega'  :  '\\omega',
        'Gamma'  :  '\\Gamma' ,
        'Delta'  :  '\\Delta' ,
        'Theta'  :  '\\Theta' ,
        'Lambda' :  '\\Lambda',
        'Xi'     :  '\\Xi'    ,
        'Pi'     :  '\\Pi'    ,
        'Sigma'  :  '\\Sigma' ,
        'Upsilon':  '\\Upsilon',
        'Phi'    :  '\\Phi'   ,
        'Psi'    :  '\\Psi'   ,
        'Omega'  :  '\\Omega' ,
        }

def greek_lookup(s):
    try:
        return greek_unicode[s]
    except KeyError:
        return s
