# Autogenerated by Wise annotation utility on 2010-08-31 20:31:36.038080

try:
    from wise.worksheet.pure_wrap import use, PureSymbol
except ImportError:
    raise Exception('Could not load Cython Pure module, perhaps it needs to be built?')

use('base','base')
# base.pure
algebra_normal = PureSymbol('algebra_normal')
cmp = PureSymbol('cmp')


