# Autogenerated by Wise annotation utility on 2010-09-06 15:04:06.234432

try:
    from wise.worksheet.pure_wrap import use, PureSymbol
except ImportError:
    raise Exception('Could not load Cython Pure module, perhaps it needs to be built?')

use('base','base')
# base.pure
algebra_normal = PureSymbol('algebra_normal')
mul_both_sides = PureSymbol('mul_both_sides')
constant = PureSymbol('constant')
exponent = PureSymbol('exponent')
add_to_both_sides = PureSymbol('add_to_both_sides')
simplify_power = PureSymbol('simplify_power')
sub_from_both_sides = PureSymbol('sub_from_both_sides')
simplify_addition = PureSymbol('simplify_addition')
sump = PureSymbol('sump')
base = PureSymbol('base')
maptox = PureSymbol('maptox')
term = PureSymbol('term')
div_both_sides = PureSymbol('div_both_sides')
simplify_rational = PureSymbol('simplify_rational')
simplify_multiplication = PureSymbol('simplify_multiplication')
cmp = PureSymbol('cmp')


