# Autogenerated by Wise annotation utility on 2010-09-03 00:43:56.917407

try:
    from wise.worksheet.pure_wrap import use, PureSymbol
except ImportError:
    raise Exception('Could not load Cython Pure module, perhaps it needs to be built?')

use('base','base')
# base.pure
algebra_normal = PureSymbol('algebra_normal')
maptox = PureSymbol('maptox')
cmp = PureSymbol('cmp')


